#!/bin/bash
###############################################################################
# Work2U WhatsApp Service - Railway Setup Script
# Run this AFTER creating GitHub repo
#
# Usage: ./setup-railway.sh
###############################################################################

set -e

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Work2U WhatsApp Service - Railway Setup                 ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Step 1: Check requirements
echo "✓ Checking requirements..."

if ! command -v node >/dev/null 2>&1; then
  echo "❌ Node.js not found. Install Node.js 18+ first:"
  echo "   curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -"
  echo "   sudo apt install -y nodejs"
  exit 1
fi
echo "  ✓ Node.js $(node --version)"

if ! command -v npm >/dev/null 2>&1; then
  echo "❌ npm not found"
  exit 1
fi
echo "  ✓ npm $(npm --version)"

# Step 2: Generate random secrets
echo ""
echo "✓ Generating secure random secrets..."
API_KEY="work2u_$(openssl rand -hex 24)"
WEBHOOK_SECRET="$(openssl rand -hex 24)"
echo "  ✓ API_KEY generated (length: ${#API_KEY})"
echo "  ✓ WEBHOOK_SECRET generated (length: ${#WEBHOOK_SECRET})"

# Step 3: Save secrets to local file (NOT pushed to git)
cat > .env << EOF
# Generated by setup script
API_KEY=$API_KEY
WEBHOOK_URL=https://crm.work2u.io/api/whatsapp/webhook
WEBHOOK_SECRET=$WEBHOOK_SECRET
PORT=3000
RATE_LIMIT=30
EOF

echo "  ✓ Secrets saved to .env (NOT pushed to git)"

# Step 4: Create railway.json (auto-config)
echo ""
echo "✓ Creating railway.json..."
cat > railway.json << EOF
{
  "$schema": "https://railway.com/railway.schema.json",
  "build": {
    "builder": "NIXPACKS"
  },
  "deploy": {
    "startCommand": "node src/server.js",
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10
  }
}
EOF

echo "  ✓ railway.json created"

# Step 5: Create Procfile (alternative)
cat > Procfile << EOF
web: node src/server.js
EOF

echo "  ✓ Procfile created"

# Step 6: Install dependencies
echo ""
echo "✓ Installing npm dependencies..."
npm install --omit=dev 2>&1 | tail -3

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ✅ Setup Complete!                                       ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Next steps:"
echo ""
echo "1. Push code to GitHub:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Work2U WhatsApp'"
echo "   git remote add origin https://github.com/YOUR_USER/work2u-whatsapp-service.git"
echo "   git push -u origin main"
echo ""
echo "2. Deploy ke Railway:"
echo "   - Buka https://railway.app/new"
echo "   - Click 'Deploy from GitHub repo'"
echo "   - Pilih 'work2u-whatsapp-service'"
echo ""
echo "3. Add these variables in Railway (tab Variables):"
echo "   API_KEY=$API_KEY"
echo "   WEBHOOK_URL=https://crm.work2u.io/api/whatsapp/webhook"
echo "   WEBHOOK_SECRET=$WEBHOOK_SECRET"
echo ""
echo "4. Add Volume (tab Settings → Volumes):"
echo "   Mount path: /app/auth"
echo "   Size: 1 GB"
echo ""
echo "5. Get public URL (Settings → Networking → Generate Domain)"
echo ""
echo "6. Paste Railway URL + API_KEY dalam dashboard WhatsApp settings"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🔐 Secrets saved locally (NOT pushed):"
echo "   .env (for local reference only)"
echo ""
echo "⚠️  IMPORTANT: Don't share these publicly!"
echo "═══════════════════════════════════════════════════════════"